/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "fr" | "en" | "de" | "it" | "es" | "nl";

export const languages: { code: Language; label: string; short: string }[] = [
  { code: "fr", label: "Français", short: "FR" },
  { code: "en", label: "English", short: "EN" },
  { code: "de", label: "Deutsch", short: "DE" },
  { code: "it", label: "Italiano", short: "IT" },
  { code: "es", label: "Español", short: "ES" },
  { code: "nl", label: "Nederlands", short: "NL" },
];

const fr = {
  home: "Accueil", language: "Langue", heroTitle: "Authentifie ton ticket Transcash ou autre.",
  heroText: "Votre plateforme de confiance pour une assistance sécurisée concernant Transcash, Neosurf, Apple Gift Card, Steam Card, Google Play Card et Paysafecard.",
  heroAlt: "Moyens de paiement numériques", methodsTitle: "Méthodes de paiement acceptées",
  methodsText: "Choisissez parmi notre large gamme d’options de paiement sécurisées",
  appleDesc: "Un outil de paiement simple, sécurisé et personnalisé pour vos achats quotidiens.",
  neosurfDesc: "Avec Neosurf, profitez d’une expérience de paiement simple et sécurisée, où que vous soyez.",
  transcashDesc: "Bienvenue chez Transcash, la solution de paiement facile et sécurisée sans banque.",
  steamDesc: "Obtenez de l’aide concernant votre carte cadeau Steam et sa référence.",
  googleDesc: "Signalez un problème lié à votre carte cadeau Google Play en toute sécurité.",
  paysafeDesc: "Recevez de l’assistance pour l'authentification de vôtre carte Paysafecard.",
  formSectionTitle: "Soumettez vos détails de recharge", formSectionText: "Remplissez le formulaire ci-dessous pour traiter votre recharge. Nous vous enverrons une confirmation à votre adresse e-mail une fois terminé.",
  guarantees: "Nos garanties", guarantee1: "Traitement instantané de votre recharge", guarantee2: "Options de paiement sécurisées multiples", guarantee3: "Confirmation par e-mail pour toutes les transactions", guarantee4: "Support client 24 h/24, 7 j/7",
  requestTitle: "Demande d’assistance", requestIntro: "Renseignez les informations demandées.",
  fullName: "Nom et prénom", fullNamePlaceholder: "Votre pseudo ou nom complet", email: "Adresse e-mail", payment: "Moyen de paiement concerné", select: "Sélectionnez une option", other: "Autre", amount: "Montant concerné", amountPlaceholder: "Exemple : 50", reference: "Saisissez les 12 caractères de la référence", referencePlaceholder: "Exemple : 254785496584", consent: "J’accepte que mes informations soient utilisées pour traiter ma demande.", sending: "Envoi en cours…", send: "Envoyer ma demande", success: "Votre demande a bien été envoyée.", error: "Votre demande n’a pas pu être envoyée. Veuillez réessayer.", bot: "Ne remplissez pas ce champ :",
  footerText: "Simplification de la gestion des recharges grâce à un service sécurisé et fiable depuis 2023.", quickLinks: "Liens rapides", about: "À propos", services: "Services", blogs: "Blog", faq: "FAQ", support: "Assistance", help: "Centre d’aide", terms: "Conditions d’utilisation", privacy: "Politique de confidentialité", contact: "Nous contacter", contactInfo: "Coordonnées", rights: "Tous droits réservés."
};

type TranslationKey = keyof typeof fr;
type Translation = Record<TranslationKey, string>;

const en: Translation = {
  home: "Home", language: "Language", heroTitle: "Check your Transcash ticket or another voucher.", heroText: "Your trusted platform for secure assistance with TransCash, Neosurf, Apple Gift Card, Steam Card, Google Play Card and Paysafecard.", heroAlt: "Digital payment methods", methodsTitle: "Accepted payment methods", methodsText: "Choose from our wide range of secure payment options", appleDesc: "A simple, secure and personalised payment tool for your everyday purchases.", neosurfDesc: "With Neosurf, enjoy a simple and secure payment experience wherever you are.", transcashDesc: "Welcome to TransCash, the easy and secure bank-free payment solution!", steamDesc: "Get help with your Steam gift card and its reference.", googleDesc: "Report an issue with your Google Play gift card securely.", paysafeDesc: "Get assistance with your payment or Paysafecard.", formSectionTitle: "Submit your top-up details", formSectionText: "Complete the form below to process your top-up. We will send a confirmation to your email address once completed.", guarantees: "Our guarantees", guarantee1: "Instant processing of your top-up", guarantee2: "Multiple secure payment options", guarantee3: "Email confirmation for every transaction", guarantee4: "24/7 customer support", requestTitle: "Support request", requestIntro: "Enter the requested information without sharing your full code or PIN.", fullName: "Full name", fullNamePlaceholder: "Your username or full name", email: "Email address", payment: "Payment method concerned", select: "Select an option", other: "Other", amount: "Amount concerned", amountPlaceholder: "Example: 50", reference: "Enter all 12 characters of the reference", referencePlaceholder: "Example: 254785496584", consent: "I agree that my information may be used to process my request.", sending: "Sending…", send: "Send my request", success: "Your request has been sent successfully.", error: "Your request could not be sent. Please try again.", bot: "Do not fill in this field:", footerText: "Making top-up management easier with a secure and reliable service since 2023.", quickLinks: "Quick links", about: "About us", services: "Services", blogs: "Blog", faq: "FAQ", support: "Support", help: "Help centre", terms: "Terms of service", privacy: "Privacy policy", contact: "Contact us", contactInfo: "Contact details", rights: "All rights reserved."
};

const de: Translation = {
  home: "Startseite", language: "Sprache", heroTitle: "Prüfen Sie Ihr Transcash-Ticket oder einen anderen Gutschein.", heroText: "Ihre vertrauenswürdige Plattform für sichere Hilfe zu TransCash, Neosurf, Apple Gift Card, Steam Card, Google Play Card und Paysafecard.", heroAlt: "Digitale Zahlungsmethoden", methodsTitle: "Akzeptierte Zahlungsmethoden", methodsText: "Wählen Sie aus unserem breiten Angebot sicherer Zahlungsoptionen", appleDesc: "Ein einfaches, sicheres und personalisiertes Zahlungsmittel für Ihre täglichen Einkäufe.", neosurfDesc: "Mit Neosurf bezahlen Sie überall einfach und sicher.", transcashDesc: "Willkommen bei TransCash, der einfachen und sicheren Zahlungslösung ohne Bank!", steamDesc: "Erhalten Sie Hilfe zu Ihrer Steam-Geschenkkarte und deren Referenz.", googleDesc: "Melden Sie sicher ein Problem mit Ihrer Google-Play-Geschenkkarte.", paysafeDesc: "Erhalten Sie Hilfe zu Ihrer Zahlung oder Paysafecard.", formSectionTitle: "Guthabendaten übermitteln", formSectionText: "Füllen Sie das folgende Formular aus. Nach Abschluss senden wir eine Bestätigung an Ihre E-Mail-Adresse.", guarantees: "Unsere Garantien", guarantee1: "Sofortige Bearbeitung Ihrer Aufladung", guarantee2: "Mehrere sichere Zahlungsoptionen", guarantee3: "E-Mail-Bestätigung für alle Transaktionen", guarantee4: "Kundendienst rund um die Uhr", requestTitle: "Supportanfrage", requestIntro: "Geben Sie die angeforderten Informationen ein, ohne Ihren vollständigen Code oder Ihre PIN mitzuteilen.", fullName: "Vor- und Nachname", fullNamePlaceholder: "Benutzername oder vollständiger Name", email: "E-Mail-Adresse", payment: "Betroffene Zahlungsmethode", select: "Option auswählen", other: "Andere", amount: "Betroffener Betrag", amountPlaceholder: "Beispiel: 50", reference: "Alle 12 Zeichen der Referenz eingeben", referencePlaceholder: "Beispiel: 254785496584", consent: "Ich stimme zu, dass meine Daten zur Bearbeitung meiner Anfrage verwendet werden.", sending: "Wird gesendet…", send: "Anfrage senden", success: "Ihre Anfrage wurde erfolgreich gesendet.", error: "Ihre Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.", bot: "Dieses Feld nicht ausfüllen:", footerText: "Einfache Verwaltung von Aufladungen durch einen sicheren und zuverlässigen Service seit 2023.", quickLinks: "Schnelllinks", about: "Über uns", services: "Leistungen", blogs: "Blog", faq: "FAQ", support: "Support", help: "Hilfe-Center", terms: "Nutzungsbedingungen", privacy: "Datenschutz", contact: "Kontakt", contactInfo: "Kontaktdaten", rights: "Alle Rechte vorbehalten."
};

const it: Translation = {
  home: "Home", language: "Lingua", heroTitle: "Verifica il tuo ticket Transcash o un altro buono.", heroText: "La tua piattaforma di fiducia per un’assistenza sicura su TransCash, Neosurf, Apple Gift Card, Steam Card, Google Play Card e Paysafecard.", heroAlt: "Metodi di pagamento digitali", methodsTitle: "Metodi di pagamento accettati", methodsText: "Scegli tra la nostra vasta gamma di opzioni di pagamento sicure", appleDesc: "Uno strumento di pagamento semplice, sicuro e personalizzato per gli acquisti quotidiani.", neosurfDesc: "Con Neosurf, paga in modo semplice e sicuro ovunque ti trovi.", transcashDesc: "Benvenuto su TransCash, la soluzione di pagamento facile e sicura senza banca!", steamDesc: "Ricevi assistenza per la tua carta regalo Steam e il suo riferimento.", googleDesc: "Segnala in sicurezza un problema con la tua carta regalo Google Play.", paysafeDesc: "Ricevi assistenza per il pagamento o la Paysafecard.", formSectionTitle: "Invia i dettagli della ricarica", formSectionText: "Compila il modulo seguente per elaborare la ricarica. Al termine invieremo una conferma al tuo indirizzo e-mail.", guarantees: "Le nostre garanzie", guarantee1: "Elaborazione immediata della ricarica", guarantee2: "Diverse opzioni di pagamento sicure", guarantee3: "Conferma via e-mail per tutte le transazioni", guarantee4: "Assistenza clienti 24/7", requestTitle: "Richiesta di assistenza", requestIntro: "Inserisci le informazioni richieste senza comunicare il codice completo o il PIN.", fullName: "Nome e cognome", fullNamePlaceholder: "Nome utente o nome completo", email: "Indirizzo e-mail", payment: "Metodo di pagamento interessato", select: "Seleziona un’opzione", other: "Altro", amount: "Importo interessato", amountPlaceholder: "Esempio: 50", reference: "Inserisci tutti i 12 caratteri del riferimento", referencePlaceholder: "Esempio: 254785496584", consent: "Accetto che i miei dati siano utilizzati per elaborare la richiesta.", sending: "Invio…", send: "Invia la richiesta", success: "La richiesta è stata inviata correttamente.", error: "Impossibile inviare la richiesta. Riprova.", bot: "Non compilare questo campo:", footerText: "Gestione semplificata delle ricariche con un servizio sicuro e affidabile dal 2023.", quickLinks: "Link rapidi", about: "Chi siamo", services: "Servizi", blogs: "Blog", faq: "FAQ", support: "Assistenza", help: "Centro assistenza", terms: "Termini di servizio", privacy: "Informativa sulla privacy", contact: "Contattaci", contactInfo: "Contatti", rights: "Tutti i diritti riservati."
};

const es: Translation = {
  home: "Inicio", language: "Idioma", heroTitle: "Verifica tu ticket Transcash u otro vale.", heroText: "Tu plataforma de confianza para recibir asistencia segura sobre TransCash, Neosurf, Apple Gift Card, Steam Card, Google Play Card y Paysafecard.", heroAlt: "Métodos de pago digitales", methodsTitle: "Métodos de pago aceptados", methodsText: "Elige entre nuestra amplia gama de opciones de pago seguras", appleDesc: "Una herramienta de pago sencilla, segura y personalizada para tus compras diarias.", neosurfDesc: "Con Neosurf, disfruta de pagos sencillos y seguros estés donde estés.", transcashDesc: "¡Bienvenido a TransCash, la solución de pago fácil y segura sin banco!", steamDesc: "Obtén ayuda con tu tarjeta regalo Steam y su referencia.", googleDesc: "Informa de forma segura sobre un problema con tu tarjeta regalo Google Play.", paysafeDesc: "Recibe asistencia con tu pago o Paysafecard.", formSectionTitle: "Envía los datos de tu recarga", formSectionText: "Completa el formulario para procesar tu recarga. Te enviaremos una confirmación por correo electrónico cuando termine.", guarantees: "Nuestras garantías", guarantee1: "Procesamiento instantáneo de tu recarga", guarantee2: "Varias opciones de pago seguras", guarantee3: "Confirmación por correo de todas las transacciones", guarantee4: "Atención al cliente 24/7", requestTitle: "Solicitud de asistencia", requestIntro: "Introduce la información solicitada sin compartir el código completo ni el PIN.", fullName: "Nombre y apellidos", fullNamePlaceholder: "Tu usuario o nombre completo", email: "Correo electrónico", payment: "Método de pago afectado", select: "Selecciona una opción", other: "Otro", amount: "Importe afectado", amountPlaceholder: "Ejemplo: 50", reference: "Introduce los 12 caracteres de la referencia", referencePlaceholder: "Ejemplo: 254785496584", consent: "Acepto que mis datos se utilicen para tramitar mi solicitud.", sending: "Enviando…", send: "Enviar mi solicitud", success: "Tu solicitud se ha enviado correctamente.", error: "No se ha podido enviar tu solicitud. Inténtalo de nuevo.", bot: "No rellenes este campo:", footerText: "Simplificamos la gestión de recargas con un servicio seguro y fiable desde 2023.", quickLinks: "Enlaces rápidos", about: "Sobre nosotros", services: "Servicios", blogs: "Blog", faq: "FAQ", support: "Asistencia", help: "Centro de ayuda", terms: "Condiciones del servicio", privacy: "Política de privacidad", contact: "Contacto", contactInfo: "Datos de contacto", rights: "Todos los derechos reservados."
};

const nl: Translation = {
  home: "Home", language: "Taal", heroTitle: "Controleer je Transcash-ticket of een andere voucher.", heroText: "Jouw betrouwbare platform voor veilige hulp bij Transcash, Neosurf, Apple Gift Card, Steam Card, Google Play Card en Paysafecard.", heroAlt: "Digitale betaalmethoden", methodsTitle: "Geaccepteerde betaalmethoden", methodsText: "Kies uit ons ruime aanbod aan veilige betaalmogelijkheden", appleDesc: "Een eenvoudig, veilig en persoonlijk betaalmiddel voor je dagelijkse aankopen.", neosurfDesc: "Geniet met Neosurf overal van een eenvoudige en veilige betaalervaring.", transcashDesc: "Welkom bij Transcash, de eenvoudige en veilige betaaloplossing zonder bank.", steamDesc: "Krijg hulp met je Steam-cadeaukaart en de bijbehorende referentie.", googleDesc: "Meld veilig een probleem met je Google Play-cadeaukaart.", paysafeDesc: "Krijg hulp bij de verificatie van je Paysafecard.", formSectionTitle: "Dien je opwaardeergegevens in", formSectionText: "Vul het onderstaande formulier in om je opwaardering te verwerken. Na afloop sturen we een bevestiging naar je e-mailadres.", guarantees: "Onze garanties", guarantee1: "Directe verwerking van je opwaardering", guarantee2: "Meerdere veilige betaalmogelijkheden", guarantee3: "Bevestiging per e-mail voor elke transactie", guarantee4: "Klantenservice 24/7", requestTitle: "Hulpverzoek", requestIntro: "Vul de gevraagde gegevens in.", fullName: "Voor- en achternaam", fullNamePlaceholder: "Je gebruikersnaam of volledige naam", email: "E-mailadres", payment: "Betreffende betaalmethode", select: "Selecteer een optie", other: "Andere", amount: "Betreffend bedrag", amountPlaceholder: "Voorbeeld: 50", reference: "Voer de 12 tekens van de referentie in", referencePlaceholder: "Voorbeeld: 254785496584", consent: "Ik ga ermee akkoord dat mijn gegevens worden gebruikt om mijn verzoek te verwerken.", sending: "Bezig met verzenden…", send: "Mijn verzoek verzenden", success: "Je verzoek is succesvol verzonden.", error: "Je verzoek kon niet worden verzonden. Probeer het opnieuw.", bot: "Vul dit veld niet in:", footerText: "Eenvoudig beheer van opwaarderingen met een veilige en betrouwbare service sinds 2023.", quickLinks: "Snelle links", about: "Over ons", services: "Diensten", blogs: "Blog", faq: "FAQ", support: "Ondersteuning", help: "Helpcentrum", terms: "Gebruiksvoorwaarden", privacy: "Privacybeleid", contact: "Contact opnemen", contactInfo: "Contactgegevens", rights: "Alle rechten voorbehouden."
};

const translations: Record<Language, Translation> = { fr, en, de, it, es, nl };
type I18nContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: TranslationKey) => string };
const I18nContext = createContext<I18nContextValue | null>(null);

export const I18nProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("verifcash-language") as Language | null;
    if (saved && languages.some(({ code }) => code === saved)) return saved;
    const browserLanguage = navigator.language.slice(0, 2) as Language;
    return languages.some(({ code }) => code === browserLanguage) ? browserLanguage : "fr";
  });
  useEffect(() => { localStorage.setItem("verifcash-language", language); document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (key: TranslationKey) => translations[language][key] }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
};

export const useI18n = () => {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used inside I18nProvider");
  return context;
};
